name: Code Quality
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install --upgrade pip
    - run: pip install Cython
    - run: pip install .[dev]
    - run: mypy document_search/
    - run: ruff check document_search/ --config pyproject.toml
    - run: isort --check document_search/